In [13]:
import pandas as pd
import re

In [2]:
df = pd.read_csv('new_tuned_references.csv')
df.tail()

,paper_name_infor,institution_infor,author_infor,journal_infor,dont_know_infor,page_infor,year_infor,field_infor,cited_infor,char_refer,degree_refer,journal_refer,name_refer,paper_refer,school_refer,year_refer,raw_refer
37242,"Corporate Diversification, Relatedness, and Fi...",한국증권학회,"배성철 , 권택호 , 이장우",Asia-Pacific Journal of Financial Studies,37(6),pp.1025~1064,2008,경영학,피인용횟수 : 20,[기타자료],NaN,"Working paper, Harvard University,","Villalonga, Belen",Does Diversification Cause the “Diversificatio...,NaN,1999.0,"40. [기타자료] - Villalonga, Belen / 1999 / Does D..."
37243,"Corporate Diversification, Relatedness, and Fi...",한국증권학회,"배성철 , 권택호 , 이장우",Asia-Pacific Journal of Financial Studies,37(6),pp.1025~1064,2008,경영학,피인용횟수 : 20,[학술지(정기간행물)],NaN,"Journal of Finance 59 : 479 ~ 506,","Villalonga, Belen",Diversification discount or premium? New Evide...,NaN,2004.0,"41. [학술지(정기간행물)] - Villalonga, Belen / 2004 / ..."
37244,"Corporate Diversification, Relatedness, and Fi...",한국증권학회,"배성철 , 권택호 , 이장우",Asia-Pacific Journal of Financial Studies,37(6),pp.1025~1064,2008,경영학,피인용횟수 : 20,[학술지(정기간행물)],NaN,"Financial Management 33 : 5 ~ 27,","Villalonga, Belen",Does Diversification Cause the Diversification...,NaN,2004.0,"42. [학술지(정기간행물)] - Villalonga, Belen / 2004 / ..."
37245,"Corporate Diversification, Relatedness, and Fi...",한국증권학회,"배성철 , 권택호 , 이장우",Asia-Pacific Journal of Financial Studies,37(6),pp.1025~1064,2008,경영학,피인용횟수 : 20,[학술지(정기간행물)],NaN,"St. John’s Review 44 : 66 ~ 80,","Weston, J. F",The Nature and Significance of Conglomerate Firms,NaN,1970.0,"43. [학술지(정기간행물)] - Weston, J. F / 1970 / The N..."
37246,"Corporate Diversification, Relatedness, and Fi...",한국증권학회,"배성철 , 권택호 , 이장우",Asia-Pacific Journal of Financial Studies,37(6),pp.1025~1064,2008,경영학,피인용횟수 : 20,[학술지(정기간행물)],NaN,Journal of Finance 56 : 1667 ~ 1691,"Whited, Toni M",Is It Inefficient Investment That Causes the D...,NaN,2001.0,"44. [학술지(정기간행물)] - Whited, Toni M / 2001 / Is ..."

# 저널별 논문 수 , 피인용 논문 수 파악하는 데이터 프레임 생성

In [18]:
df['cited_count_infor'] = [int(','.join(re.findall('\d',val)).replace(",",'')) for val in df['cited_infor']]

In [20]:
df.tail(1)

,paper_name_infor,institution_infor,author_infor,journal_infor,dont_know_infor,page_infor,year_infor,field_infor,cited_infor,char_refer,degree_refer,journal_refer,name_refer,paper_refer,school_refer,year_refer,raw_refer,cited_count_infor
37246,"Corporate Diversification, Relatedness, and Fi...",한국증권학회,"배성철 , 권택호 , 이장우",Asia-Pacific Journal of Financial Studies,37(6),pp.1025~1064,2008,경영학,피인용횟수 : 20,[학술지(정기간행물)],NaN,Journal of Finance 56 : 1667 ~ 1691,"Whited, Toni M",Is It Inefficient Investment That Causes the D...,NaN,2001.0,"44. [학술지(정기간행물)] - Whited, Toni M / 2001 / Is ...",20

In [37]:
first_groupby_df = df.groupby(by='institution_infor').aggregate({'paper_name_infor':'unique','char_refer':'count'})
first_groupby_df

,paper_name_infor,char_refer
institution_infor,,
한국재무관리학회,"[정보비대칭과 신용등급 변경 공표의 효과, 한국주식시장의 배당규모와 기업가치간 비선...",10990
한국재무학회,"[한국 주식 수익률의 장기 반전현상에 관한 연구, 손해보험을 이용한 헤징과 기업가치...",7343
한국증권학회,"[발생액 이상현상과 차익거래기회에 관한 연구, 신용평가등급과 발생액 및 보수주의 이...",12794
한국파생상품학회,"[날씨 파생상품을 이용한 국내 도시가스 산업의 날씨 위험 관리, 종가단일가에 기초한...",5878

In [39]:
first_groupby_df['citing_paper_count'] = [len(i) for i in first_groupby_df['paper_name_infor']]

In [44]:
groupby_df = first_groupby_df.iloc[:,1:]
groupby_df.columns = ['cited_paper_num','citing_paper_num']
groupby_df['cited_paper_per_citing_paper'] = groupby_df['cited_paper_num'] / groupby_df['citing_paper_num']
groupby_df

,cited_paper_num,citing_paper_num,cited_paper_per_citing_paper
institution_infor,,,
한국재무관리학회,10990,427,25.737705
한국재무학회,7343,185,39.691892
한국증권학회,12794,502,25.486056
한국파생상품학회,5878,254,23.141732

# 연도별 인용 , 피인용 논문 갯수 파악하는 데이터 프레임

In [45]:
df.tail(1)

,paper_name_infor,institution_infor,author_infor,journal_infor,dont_know_infor,page_infor,year_infor,field_infor,cited_infor,char_refer,degree_refer,journal_refer,name_refer,paper_refer,school_refer,year_refer,raw_refer,cited_count_infor
37246,"Corporate Diversification, Relatedness, and Fi...",한국증권학회,"배성철 , 권택호 , 이장우",Asia-Pacific Journal of Financial Studies,37(6),pp.1025~1064,2008,경영학,피인용횟수 : 20,[학술지(정기간행물)],NaN,Journal of Finance 56 : 1667 ~ 1691,"Whited, Toni M",Is It Inefficient Investment That Causes the D...,NaN,2001.0,"44. [학술지(정기간행물)] - Whited, Toni M / 2001 / Is ...",20

In [46]:
first_groupby_df = df.groupby(by='year_infor').aggregate({'paper_name_infor':'unique','char_refer':'count'})
first_groupby_df

                                             paper_name_infor  char_refer
year_infor
2002        [주식시장 동조화와 다운사이드 리스크, 비대칭 변동성 추정모형의 새로운 대안 : S...           0
2003        [벤처캐피탈 투자재원의 구성과 투자행태, OECD 국가들의 은행산업 효율성변화 및 ...           0
2004        [스톡옵션과 기업지배구조, 기업의 IR활동과 주가행태:거래소시장과 코스닥시장의 비교...        1366
2005        [한국주식시장에서 사전적 투명성과 질적 수준과의 관계: 호가공개범위 확대를 중심으로...        1322
2006        [주택저당증권(MBS)의 발행구조에 관한 연구 : 다양한 MBS 구조설계를 중심으로...        1445
2007        [한국주식시장에서 주식형 펀드의 성과결정요인에 관한 연구, 자사주매입에 관한 잉여현...        1502
2008        [한국 주식 수익률의 장기 반전현상에 관한 연구, 자기주식매입의 유상증자에 대한 신...        2135
2009        [발생액 이상현상과 차익거래기회에 관한 연구, 신용평가등급과 발생액 및 보수주의 이...        1931
2010        [ELW 시장에서의 유동성공급자 간 차이, 주식분할 후 변동성 증가와 거래행태의 변...        2169
2011        [ELW 시장의 투자자 인식과 투자행태 분석, 소비습관과 주식수익률 프리미엄 현상 ...        3007
2012        [애널리스트 활동수준에 따른 애널리스트보고서의 정보력과 투자주체별 정보비대칭, 국민...        2504
2013        [기대수익률에 대한 비대칭적 디스포지션 효과, 파생상품사용과 이익관리가 한국기업의환...        2925
2014        [저변동성 이상현상과 투자전략의 수익성 검증, 회계 정보를 활용한 사건연구에서의 초...        4501
2015        [자본시장의 발달 정도에 따른 합병의 규모효과와 다각화 디스카운트, IPO 신디케이...        4315
2016        [우리사주제도와 기업가치: 무상출연의 효과에 관한 실증연구, 국제간 합병의 규모효과...        4061
2017        [한국 주식시장에서 공매도거래 유인: 유가증권시장과 코스닥시장 분석, 무상증자에 대...        3822
2018        [구성자산 특성이 ETF 가격효율성에 미치는 효과, ELW 시장을 통해 살펴 본 시...           0

In [47]:
first_groupby_df['citing_paper_count'] = [len(i) for i in first_groupby_df['paper_name_infor']]

In [48]:
groupby_df = first_groupby_df.iloc[:,1:]
groupby_df.columns = ['cited_paper_num','citing_paper_num']
groupby_df['cited_paper_per_citing_paper'] = groupby_df['cited_paper_num'] / groupby_df['citing_paper_num']
groupby_df

            cited_paper_num  citing_paper_num  cited_paper_per_citing_paper
year_infor
2002                      0                73                      0.000000
2003                      0                75                      0.000000
2004                   1366                77                     17.740260
2005                   1322                57                     23.192982
2006                   1445                64                     22.578125
2007                   1502                65                     23.107692
2008                   2135                67                     31.865672
2009                   1931                65                     29.707692
2010                   2169                70                     30.985714
2011                   3007                90                     33.411111
2012                   2504                79                     31.696203
2013                   2925                92                     31.793478
2014                   4501               110                     40.918182
2015                   4315               110                     39.227273
2016                   4061               102                     39.813725
2017                   3822               104                     36.750000
2018                      0                68                      0.000000

# 각 저널별로 몇 년도 부터 몇 년도까지의 인용논문이 있는지 파악하는 데이터 프레임

In [49]:
df.tail(1)

,paper_name_infor,institution_infor,author_infor,journal_infor,dont_know_infor,page_infor,year_infor,field_infor,cited_infor,char_refer,degree_refer,journal_refer,name_refer,paper_refer,school_refer,year_refer,raw_refer,cited_count_infor
37246,"Corporate Diversification, Relatedness, and Fi...",한국증권학회,"배성철 , 권택호 , 이장우",Asia-Pacific Journal of Financial Studies,37(6),pp.1025~1064,2008,경영학,피인용횟수 : 20,[학술지(정기간행물)],NaN,Journal of Finance 56 : 1667 ~ 1691,"Whited, Toni M",Is It Inefficient Investment That Causes the D...,NaN,2001.0,"44. [학술지(정기간행물)] - Whited, Toni M / 2001 / Is ...",20

In [57]:
year_infor_df = df.groupby('institution_infor').aggregate({'year_infor':'unique'})
year_infor_df['year_infor_tuned'] = [set(i) for i in year_infor_df['year_infor']]
year_infor_df['count_year_infor'] = [len(i) for i in year_infor_df['year_infor_tuned']]
year_infor_df = year_infor_df.iloc[:,1:]
year_infor_df

,year_infor_tuned,count_year_infor
institution_infor,,
한국재무관리학회,"{2016, 2017, 2018, 2002, 2003, 2004, 2005, 200...",17
한국재무학회,"{2016, 2017, 2018, 2002, 2003, 2004, 2005, 200...",15
한국증권학회,"{2016, 2017, 2018, 2002, 2003, 2004, 2005, 200...",17
한국파생상품학회,"{2016, 2017, 2018, 2002, 2003, 2004, 2005, 200...",17

# 한국재무학회가 2002~2018년도까지 데이터 중 2006년 2007년 데이터가 없다.

In [62]:
year_infor_df.iat[1,0]

{2002,
 2003,
 2004,
 2005,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018}