In [88]:
import pandas as pd
from IPython.display import display

In [102]:
df1 = pd.read_csv('KOSPI_BETA_MONTHLY.csv',encoding = "ISO-8859-1")
df2 = pd.read_csv('KOSPI_SILH_SUIK_RT_WITH_DIVIDEND_MONTHLY.csv',encoding = "ISO-8859-1")
df1.shape , df2.shape

((358, 769), (358, 759))

In [104]:
df1.index = df1.iloc[:,0]
df1 = df1.iloc[12:,1:]
df1.columns =  ['stock'+str(idx) for idx,val in enumerate(df1.columns)]
df1.fillna(0,inplace=True)
display(df1.tail())

df2.index = df2.iloc[:,0]
df2 = df2.iloc[12:,1:]
df2.columns =  ['stock'+str(idx) for idx,val in enumerate(df2.columns)]
df2.fillna(0,inplace=True)
display(df2.tail())

print(df1.shape , df2.shape)

,stock0,stock1,stock2,stock3,stock4,stock5,stock6,stock7,stock8,stock9,...,stock757,stock758,stock759,stock760,stock761,stock762,stock763,stock764,stock765,stock766
stock0,,,,,,,,,,,,,,,,,,,,,
0.072290,0.946680,1.019230,0.862940,0.750590,-0.355130,0.183090,0.979490,0.576260,0.056730,2.007160,...,0,0,0,0,0,0,0,0,0,1.151850
0.072290,0.946680,1.019230,0.862940,0.750590,-0.355130,0.183090,0.979490,0.576260,0.056730,2.007160,...,0,0,0,0,0,0,0,0,0,1.151850
0.087440,0.693620,1.268160,0.757720,0.960260,0.111340,0.304170,1.082160,0.327530,0.314230,1.826130,...,0,0,0,0,0,0,0,0,0,1.406380
-0.202920,0.618380,1.365030,0.606540,0.937990,-0.018200,0.300500,1.045540,0.452560,0.036320,2.050600,...,0,0,0,0,0,0,0,0,0,1.251880
-0.202920,0.618380,1.365030,0.606540,0.937990,-0.018200,0.300500,1.045540,0.452560,0.036320,2.050600,...,0,0,0,0,0,0,0,0,0,1.251880

,stock0,stock1,stock2,stock3,stock4,stock5,stock6,stock7,stock8,stock9,...,stock748,stock749,stock750,stock751,stock752,stock753,stock754,stock755,stock756,stock757
stock0,,,,,,,,,,,,,,,,,,,,,
2018-05-31,-0.87,-4.67,8.25,-12.42,-2.15,3.15,-7.57,3.93,-4.47,-0.85,...,7.28,-12.41,0,0,0,0,0,0,0,-8.91
2018-06-30,-10.92,6.54,-16.48,6.13,-6.34,3.93,-2.48,-8.61,12.37,-7.36,...,-2.84,4.50,0,-28.70,0,0,0,0,0,-17.72
2018-07-31,8.33,3.68,-2.99,-7.94,-4.17,-4.20,-7.38,2.53,-10.12,-2.76,...,-0.90,-3.44,0.00,6.68,12.71,-10.10,-4.86,6.25,0,2.77
2018-08-31,4.98,-3.55,0.34,7.84,-0.82,-10.53,-7.69,7.17,1.99,-5.21,...,4.09,-3.46,-3.62,-2.78,12.17,-14.61,11.91,-5.88,27.31,1.93
2018-09-12,0.00,0.00,3.24,-2.91,-2.47,6.37,-1.19,0.00,8.12,-0.88,...,-8.30,2.08,1.79,8.94,-9.26,-4.47,1.69,-7.19,8.58,-2.65

(334, 767) (346, 758)