시가 총액 순위 정보

In [2]:
import requests
params={'key':'value'}
res=requests.get('http://www.tistory.com',params=params)
res.url

'https://www.tistory.com/?key=value'

params form the query string in the URL, data is used to fill the body of a request (together with files). GET and HEAD requests have no body.

For the majority of servers accepting a POST request, the data is expected to be passed in as the request body.

You need to consult the documentation for the specific API you are calling as to what they expect, but if you have to assume, assume you have to use data.

In [6]:
url

'http://companyinfo.stock.naver.com/v1/company/ajax/cF1001.aspx?cmp_cd=005930&fin_typ=4&freq_typ=Y'

In [21]:
import pandas as pd
import numpy as np
import requests
from io import BytesIO
from datetime import datetime

In [34]:
def stock_master(date=None):
    if date == None:
        date = datetime.today().strftime('%Y%m%d')
        
    gen_otp_url = 'http://marketdata.krx.co.kr/contents/COM/GenerateOTP.jspx'
    gen_otp_data={
        'name': 'fileDown',
         'filetype': 'csv',
        'url': 'MKD/04/0404/04040200/mkd04040200_01',
        'market_gubun': 'ALL',
        'indx_ind_cd': '',
        'sect_tp_cd': 'ALL',
        'schdate': date,
        'pagePath':' /contents/MKD/04/0404/04040200/MKD04040200.jsp',  
     }
        
    r = requests.post(gen_otp_url,gen_otp_data)
    code = r.content
    
    down_url = 'http://file.krx.co.kr/download.jspx'
    down_data = {'code':code}
    r=requests.post(down_url,down_data)
    df = pd.read_csv(BytesIO(r.content),header=0,thousands=',')
    return df

In [35]:
stock_master()

,순위,종목코드,종목명,현재가,대비,등락률,거래량,거래대금,시가,고가,저가,시가총액,시가총액비중(%),상장주식수(천주),외국인 보유주식수,외국인 지분율(%),총카운트
0,1,005930,삼성전자,49400,-500,-1.0,5505789,272351921650,49700,49800,49250,317114640180000,16.32,6419324700,NaN,NaN,2314.0
1,2,000660,SK하이닉스,88800,-400,-0.4,681240,60594958900,89900,90100,88200,64646610012000,3.33,728002365,NaN,NaN,NaN
2,3,005935,삼성전자우,39400,-300,-0.8,299306,11798950450,39700,39700,39300,35602982600000,1.83,903629000,NaN,NaN,NaN
3,4,068270,셀트리온,271500,4000,1.5,373859,101805993000,269500,275500,269000,34044987664500,1.75,125395903,NaN,NaN,NaN
4,5,005490,POSCO,368000,-4000,-1.1,45883,17055877500,373000,375000,366500,32084755280000,1.65,87186835,NaN,NaN,NaN
5,6,005380,현대차,140000,500,0.4,239665,33756933500,140000,142000,139500,30838707060000,1.59,220276479,NaN,NaN,NaN
6,7,207940,삼성바이오로직스,427000,7000,1.7,72613,30902982500,421000,432000,419500,28252455000000,1.45,66165000,NaN,NaN,NaN
7,8,051910,LG화학,380000,3000,0.8,140549,53523924000,380000,383500,378500,26825090340000,1.38,70592343,NaN,NaN,NaN
8,9,028260,삼성물산,127000,1500,1.2,88287,11155029000,126000,127000,125500,24090635461000,1.24,189690043,NaN,NaN,NaN
9,10,105560,KB금융,56700,-700,-1.2,425340,24475716100,58000,58100,56700,23706924147900,1.22,418111537,NaN,NaN,NaN
10,11,035420,NAVER,709000,-2000,-0.3,32914,23316978000,712000,715000,704000,23370539411000,1.20,32962679,NaN,NaN,NaN
11,12,015760,한국전력,35700,600,1.7,669366,23961817350,35250,36000,35200,22918117548900,1.18,641964077,NaN,NaN,NaN
12,13,055550,신한지주,47250,-300,-0.6,221131,10476081550,47550,47700,47000,22405930485750,1.15,474199587,NaN,NaN,NaN
13,14,051900,LG생활건강,1425000,27000,1.9,10123,14411233000,1399000,1440000,1398000,22255930725000,1.15,15618197,NaN,NaN,NaN
14,15,012330,현대모비스,225000,-1000,-0.4,68605,15474889500,225000,227000,224000,21902369175000,1.13,97343863,NaN,NaN,NaN
15,16,032830,삼성생명,103500,0,0.0,66886,6958431000,104000,105000,103500,20700000000000,1.07,200000000,NaN,NaN,NaN
16,17,034730,SK,284000,500,0.2,24324,6932101000,285500,288000,283000,19982324348000,1.03,70360297,NaN,NaN,NaN
17,18,096770,SK이노베이션,213500,-1000,-0.5,95118,20359545000,214500,216500,212500,19741397914000,1.02,92465564,NaN,NaN,NaN
18,19,017670,SK텔레콤,244000,3000,1.2,163602,39775739500,241000,245500,240000,19701953484000,1.01,80745711,NaN,NaN,NaN
19,20,090430,아모레퍼시픽,327000,-1500,-0.5,44736,14692221000,329000,331500,327000,19115926230000,0.98,58458490,NaN,NaN,NaN
20,21,018260,삼성에스디에스,227000,-3000,-1.3,28187,6411953000,229500,230500,224500,17564760600000,0.90,77377800,NaN,NaN,NaN
21,22,006400,삼성SDI,228000,4000,1.8,201326,45747282000,226500,229000,225000,15678312840000,0.81,68764530,NaN,NaN,NaN
22,23,066570,LG전자,90300,1300,1.5,309926,28005304100,89200,91400,89200,14777397604200,0.76,163647814,NaN,NaN,NaN
23,24,091990,셀트리온헬스케어,103000,3800,3.8,926102,95073255900,100400,104500,100400,14473171072000,0.74,140516224,NaN,NaN,NaN
24,25,086790,하나금융지주,45650,-600,-1.3,234039,10769999650,46250,46700,45650,13706050130300,0.71,300242062,NaN,NaN,NaN
25,26,033780,KT&G,99300,300,0.3,71705,7129690600,99500,99900,98500,13633144952100,0.70,137292497,NaN,NaN,NaN
26,27,003550,LG,78900,300,0.4,78568,6212958000,78600,79600,78200,13614757635900,0.70,172557131,NaN,NaN,NaN
27,28,000270,기아차,32800,200,0.6,439742,14686483600,32750,33750,32750,13295917781600,0.68,405363347,NaN,NaN,NaN
28,29,011170,롯데케미칼,379000,-2000,-0.5,22174,8422980000,380000,382500,377000,12990383801000,0.67,34275419,NaN,NaN,NaN
29,30,251270,넷마블,150500,-500,-0.3,43752,6621969500,151000,153000,150000,12817099827000,0.66,85163454,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2284,2285,005965,동부건설우,21700,-450,-2.0,2009,44141750,22300,22450,21650,4898384400,0.00,225732,NaN,NaN,NaN
2285,2286,001755,한양증권우,9010,50,0.6,168,1504820,8930,9040,8930,4730250000,0.00,525000,NaN,NaN,NaN
2286,2287,000547,흥국화재2우B,29950,450,1.5,3125,91414200,29500,30050,28950,4600320000,0.00,153600,NaN,NaN,NaN
2287,2288,090355,노루페인트우,9890,0,0.0,1132,11196050,9770,9900,9770,4580316140,0.00,463126,NaN,NaN,NaN
2288,2289,000995,DB하이텍1우,39000,0,0.0,267,10268550,39000,39750,38100,4380324000,0.00,112316,NaN,NaN,NaN
2289,2290,001527,동양2우B,13900,-400,-2.8,2324,32332300,13850,14200,13850,4289109100,0.00,308569,NaN,NaN,NaN
2290,2291,000145,하이트진로홀딩스우,9110,0,0.0,1,9110,9110,9110,9110,4289079100,0.00,470810,NaN,NaN,NaN
2291,2292,001067,JW중외제약2우B,47550,2950,6.6,3288,152737900,45150,47550,44650,4093959900,0.00,86098,NaN,NaN,NaN
2292,2293,00781K,코리아써키트2우B,5080,-10,-0.2,51,259580,5090,5090,5080,3981190920,0.00,783699,NaN,NaN,NaN
2293,2294,271400,알로이스,1675,0,0.0,0,0,0,0,0,3906100000,0.00,2332000,NaN,NaN,NaN
2294,2295,227420,오백볼트,510,-5,-1.0,1077,477270,438,510,438,3869847360,0.00,7587936,NaN,NaN,NaN
2295,2296,004989,성신양회3우B,13150,0,0.0,5353,70487950,13000,13500,12800,3772708700,0.00,286898,NaN,NaN,NaN
2296,2297,008355,남선알미우,12200,-150,-1.2,18232,220547650,12350,12500,11800,3756258000,0.00,307890,NaN,NaN,NaN
2297,2298,000227,유유제약2우B,22450,1400,6.6,4155,91400000,21500,22450,21200,3683596000,0.00,164080,NaN,NaN,NaN
2298,2299,002785,진흥기업우B,4195,60,1.4,2242,9468950,4105,4295,4105,3596029510,0.00,857218,NaN,NaN,NaN
2299,2300,000325,노루홀딩스우,19350,150,0.8,271,5205450,19200,19350,19200,3584587500,0.00,185250,NaN,NaN,NaN
2300,2301,208890,에듀케이션파트너,1800,0,0.0,0,0,0,0,0,3583476000,0.00,1990820,NaN,NaN,NaN
2301,2302,032685,소프트센우,24500,250,1.0,735,17871900,23950,24500,23950,3499996500,0.00,142857,NaN,NaN,NaN
2302,2303,001799,대한제당3우B,25600,600,2.4,1,25600,25600,25600,25600,3319193600,0.00,129656,NaN,NaN,NaN
2303,2304,001529,동양3우B,34700,50,0.1,2271,77126850,35050,35900,33000,3113353400,0.00,89722,NaN,NaN,NaN
2304,2305,163430,디피코,1685,0,0.0,0,0,0,0,0,3096945750,0.00,1837950,NaN,NaN,NaN
2305,2306,267810,앙츠,1790,135,8.2,100,179000,1790,1790,1790,2769130000,0.00,1547000,NaN,NaN,NaN
2306,2307,272420,극동자동화,5500,0,0.0,0,0,0,0,0,2750000000,0.00,500000,NaN,NaN,NaN
2307,2308,002787,진흥기업2우B,8920,-50,-0.6,3833,33930410,9030,9260,8790,2629687360,0.00,294808,NaN,NaN,NaN
2308,2309,135270,세종머티리얼즈,451,0,0.0,0,0,0,0,0,2471598613,0.00,5480263,NaN,NaN,NaN
2309,2310,189540,씨티네트웍스,452,0,0.0,0,0,0,0,0,1092027480,0.00,2415990,NaN,NaN,NaN
2310,2311,110660,세신버팔로,170,-13,-7.1,10000,1700000,170,170,170,1020000000,0.00,6000000,NaN,NaN,NaN
2311,2312,179720,옐로페이,71,-12,-14.5,1,71,71,71,71,798750000,0.00,11250000,NaN,NaN,NaN
2312,2313,242850,영현무역,275,0,0.0,0,0,0,0,0,445500000,0.00,1620000,NaN,NaN,NaN
2313,2314,144740,피엠디아카데미,66,0,0.0,0,0,0,0,0,114678564,0.00,1737554,NaN,NaN,NaN

In [36]:
print('종목수:',len(df))

종목수: 2251